# Generated by Django 5.1 on 2025-01-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_address_user_birth_date_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=80, unique=True, verbose_name='Email'),
        ),
    ]
