# Generated by Django 5.1 on 2025-01-06 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BREAKFAST', 'breakfast'), ('BRUNCH', 'brunch'), ('SNACK', 'snack'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('SUPPER', 'supper')], default='BREAKFAST', max_length=80)),
                ('MEAL_CHOICES', models.CharField(choices=[('VEGAN', 'vegan'), ('VEGETARIAN', 'vegetarian'), ('PALEO', 'paleo'), ('KETO', 'keto'), ('GLUTEN_FREE', 'gluten free'), ('DAIRY_FREE', 'dairy free'), ('NUT_FREE', 'nut free'), ('SHELLFISH_FREE', 'shellfish free'), ('SOY_FREE', 'soy free'), ('WHEAT_FREE', 'wheat free'), ('EGG_FREE', 'egg free'), ('FISH_FREE', 'fish free'), ('NO_RESTRICTIONS', 'no restrictions')], max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed')], default='PENDING', max_length=80)),
                ('description', models.TextField()),
                ('vitamins', models.TextField()),
                ('minerals', models.TextField()),
                ('calories', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
