# Generated by Django 5.1 on 2025-01-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='calories',
            new_name='calories_in_kcals',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='carbohydrates',
            new_name='carbohydrates_in_grams',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='fats',
            new_name='fats_in_grams',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='MEAL_CHOICES',
            new_name='meal_choices',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='status',
            new_name='meal_status',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='proteins',
            new_name='proteins_in_grams',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(default='Healthy Meal', max_length=200),
        ),
    ]
