# Generated by Django 5.1 on 2025-01-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal_ingredients_meal_recipe_alter_meal_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='Ingredients',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='Recipe',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='customer',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=80),
        ),
    ]
