# Generated by Django 5.1 on 2025-01-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_rename_calories_in_kcals_meal_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='ingredients',
            new_name='Ingredients',
        ),
    ]
