# Generated by Django 5.1 on 2025-01-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_rename_ingredients_meal_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='recipe',
            new_name='Recipe',
        ),
    ]
