# Generated by Django 5.1 on 2025-01-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_meal_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='Ingredients',
            field=models.CharField(default='Ingredients', max_length=1000),
        ),
        migrations.AlterField(
            model_name='meal',
            name='Recipe',
            field=models.CharField(default='Recipe', max_length=1000),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydrates_in_grams',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.CharField(default='Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats_in_grams',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='minerals',
            field=models.CharField(default='Minerals', max_length=1000),
        ),
        migrations.AlterField(
            model_name='meal',
            name='proteins_in_grams',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='vitamins',
            field=models.CharField(default='Vitamins', max_length=1000),
        ),
    ]
