# Generated by Django 5.1 on 2025-01-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_alter_meal_meal_choices_alter_meal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='type',
            new_name='types',
        ),
    ]
